name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: icepuma/rust-action@master
    - name: Build
      run: rustup -V && cargo build --verbose
    # - name: Run tests
    #  run: cargo test --verbose
